Task 1

In [ ]:
import numpy as np

In [ ]:
arr1 = np.empty( shape = (3,2))

In [ ]:
arr2 = np.empty( shape = (2,3))

In [ ]:
print(arr1)

[[4.66839034e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [ ]:
print(arr2)

[[4.66839034e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


Task 2

In [ ]:
arr = np.array(list(range(4,10)))

In [ ]:
arr1 = arr.reshape(3,2)

In [ ]:
arr2 = arr.reshape(2,3)

In [ ]:
print(arr1)

[[4 5]
 [6 7]
 [8 9]]


In [ ]:
print(arr2)

[[4 5 6]
 [7 8 9]]


Task 3

In [ ]:
mul = np.dot(arr1,arr2)

In [ ]:
print(mul)

[[ 51  60  69]
 [ 73  86  99]
 [ 95 112 129]]


Task 4

In [ ]:
elementMatrix = arr1 * arr2.T

In [ ]:
print(elementMatrix)

[[16 35]
 [30 56]
 [48 81]]


Task 5

In [ ]:
mean = np.mean(arr1)

In [ ]:
print(mean)

6.5


Task 6

In [36]:
import pandas as pd

data = pd.read_csv('mtcars.csv')

In [39]:
cols = data.columns

In [40]:
for i in range(1,len(cols)):
  data[cols[i]] -= np.mean(data[cols[i]])

print(data)

             Unnamed: 0        mpg     cyl  ...       am    gear    carb
0             Mazda RX4   0.909375 -0.1875  ...  0.59375  0.3125  1.1875
1         Mazda RX4 Wag   0.909375 -0.1875  ...  0.59375  0.3125  1.1875
2            Datsun 710   2.709375 -2.1875  ...  0.59375  0.3125 -1.8125
3        Hornet 4 Drive   1.309375 -0.1875  ... -0.40625 -0.6875 -1.8125
4     Hornet Sportabout  -1.390625  1.8125  ... -0.40625 -0.6875 -0.8125
5               Valiant  -1.990625 -0.1875  ... -0.40625 -0.6875 -1.8125
6            Duster 360  -5.790625  1.8125  ... -0.40625 -0.6875  1.1875
7             Merc 240D   4.309375 -2.1875  ... -0.40625  0.3125 -0.8125
8              Merc 230   2.709375 -2.1875  ... -0.40625  0.3125 -0.8125
9              Merc 280  -0.890625 -0.1875  ... -0.40625  0.3125  1.1875
10            Merc 280C  -2.290625 -0.1875  ... -0.40625  0.3125  1.1875
11           Merc 450SE  -3.690625  1.8125  ... -0.40625 -0.6875  0.1875
12           Merc 450SL  -2.790625  1.8125  ... -0.