In [1]:
import numpy as np

Training Data

In [2]:
#Input Features

X = np.array([[73, 67, 43], 
              [91, 88, 64], 
              [87, 134, 58], 
              [102, 43, 37], 
              [69, 96, 70]], dtype='float32')

In [3]:
#Target 

Y = np.array([[56], 
              [81], 
              [119], 
              [22], 
              [103]], dtype='float32')

Linear Regression Model

In [4]:
# Normalising the Input

mu = np.mean(X,0)
sigma = np.std(X,0)
X = (X-mu)/sigma
X = np.hstack((np.ones((Y.size,1)),X))
X.shape

(5, 4)

In [24]:
# Weights and biases
rg = np.random.default_rng(40)
w = rg.random((1,4))
w

array([[0.7298985 , 0.69341496, 0.94192102, 0.05965206]])

Loss Function





In [25]:
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / diff.size

# Compute error
preds = model(X,w)
cost_initial = mse(preds, Y)
print("Cost before regression: ",cost_initial)

Cost before regression:  6837.370626720728


Compute Gradients

In [26]:
# Define the model
def model(x,w):
    return x @ w.T

In [27]:
def gradient_descent(X,y,w,learning_rate, n_iters):
  J_history = np.zeros((n_iters,1))
  for i in range(n_iters):
    h = model(X,w)
    diff = h - y
    delta = (learning_rate/Y.size)*(X.T@diff)
    new_w = w - delta.T
    w=new_w
    J_history[i] = mse(h, y)
  return (J_history, w)

Train for multiple Epochs

In [28]:
import matplotlib.pyplot as plt
n_iters = 500
learning_rate = 0.01

initial_cost = mse(model(X,w),Y)

print("Initial cost is: ", initial_cost, "\n")

(J_history, optimal_params) = gradient_descent(X, Y, w, learning_rate, n_iters)

print("Optimal parameters are: \n", optimal_params, "\n")

print("Final cost is: ", J_history[-1])

Initial cost is:  6837.370626720728 

Optimal parameters are: 
 [[75.70412518 -4.36336061 24.07319285 10.53168339]] 

Final cost is:  [3.02194313]


In [29]:
# Calculate error
preds = model(X,optimal_params)
cost_final = mse(preds, Y)
# Print predictions
print("Prediction:\n",preds)
# Comparing predicted with targets
print("Targets:\n",Y)

Prediction:
 [[ 55.48881007]
 [ 83.30603533]
 [116.13863769]
 [ 20.9284231 ]
 [102.65871911]]
Targets:
 [[ 56.]
 [ 81.]
 [119.]
 [ 22.]
 [103.]]
